// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX3wbNoi8cH4NyUQIA9wTzCWFBbu25JfE',
    appId: '1:739057199710:web:716e4a0bf85b1078d662cf',
    messagingSenderId: '739057199710',
    projectId: 'crane-app-8804e',
    authDomain: 'crane-app-8804e.firebaseapp.com',
    storageBucket: 'crane-app-8804e.firebasestorage.app',
    measurementId: 'G-9J5WJP6R8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDktDmu5kI7zu0rmfAoXmP0jrw4H7EctGY',
    appId: '1:739057199710:android:b6c84e63a8965f49d662cf',
    messagingSenderId: '739057199710',
    projectId: 'crane-app-8804e',
    storageBucket: 'crane-app-8804e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvm_JAc3sdXx-uvnMEKcZu5HHoWOC3PI',
    appId: '1:739057199710:ios:c524a643e558e60cd662cf',
    messagingSenderId: '739057199710',
    projectId: 'crane-app-8804e',
    storageBucket: 'crane-app-8804e.firebasestorage.app',
    iosBundleId: 'com.example.crane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkvm_JAc3sdXx-uvnMEKcZu5HHoWOC3PI',
    appId: '1:739057199710:ios:c524a643e558e60cd662cf',
    messagingSenderId: '739057199710',
    projectId: 'crane-app-8804e',
    storageBucket: 'crane-app-8804e.firebasestorage.app',
    iosBundleId: 'com.example.crane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX3wbNoi8cH4NyUQIA9wTzCWFBbu25JfE',
    appId: '1:739057199710:web:82848901564b6773d662cf',
    messagingSenderId: '739057199710',
    projectId: 'crane-app-8804e',
    authDomain: 'crane-app-8804e.firebaseapp.com',
    storageBucket: 'crane-app-8804e.firebasestorage.app',
    measurementId: 'G-PHMW38RZ4V',
  );
}
